version: "3"
services:
  api:
    build: .
    environment:
      APP_PORT: 10001
      DATABASE_URI: mongodb://mongo:27017/badge-it
      GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
    ports:
      - 10001:10001
    depends_on:
      - mongo
  mongo:
    image: mongo:4