name: Lint and Deploy

on: 
  push:
    branches: [ master, rewrite ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}
  
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        if: steps.cache-node-modules.outputs.cache-hit != 'true'

      - run: yarn lint
    
  build: # -and-deploy:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: azure/docker-login@v1
        with:
          login-server: index.docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: yarn docker

      # - run: yarn deploy